# Generated by Django 3.1.6 on 2021-08-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.patient', verbose_name='Пациент'),
        ),
    ]
