# Generated by Django 3.1.6 on 2021-08-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210822_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_patient', to='appointment.patient', verbose_name='Пациент'),
        ),
    ]
