# Generated by Django 3.2.7 on 2021-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('specialty', models.CharField(max_length=50, verbose_name='Специальность')),
                ('work_experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
            ],
        ),
    ]
