# Generated by Django 3.1.5 on 2021-01-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('specialty', models.CharField(max_length=50, verbose_name='Специальность')),
                ('work_experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
            ],
        ),
        migrations.CreateModel(
            name='Card_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('comment', models.TextField(max_length=50, verbose_name='Отзыв')),
                ('data', models.DateField(verbose_name='Дата')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.card', verbose_name='Врач')),
            ],
        ),
    ]
