# Generated by Django 3.1.5 on 2021-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210206_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_comments',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
