# Generated by Django 3.1.6 on 2021-08-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('token', models.CharField(max_length=50, verbose_name='Token')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profilepatient',
            name='insurance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страховой полис'),
        ),
    ]
