# Generated by Django 3.1.6 on 2021-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210823_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=15)),
                ('url', models.URLField()),
            ],
        ),
    ]
