# Generated by Django 3.1.6 on 2021-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mail_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_domains',
            name='name_mail',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
