# Generated by Django 3.1.5 on 2021-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.DateField(default='2010-10-10', verbose_name='Дата рождения'),
        ),
    ]
