# Generated by Django 3.1.5 on 2021-02-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/no_foto.jpg', upload_to='static/', verbose_name='Фото'),
        ),
    ]
